#define COMBO_PROCESS_KEY_REPRESS
// #define COMBO_ONLY_FROM_LAYER 0
#define COMBO_MUST_HOLD_PER_COMBO
//#define COMBO_HOLD_TERM 100
// #define COMBO_TERM 40
#define KEY_PRESS_DELAY_OLED_ENABLE
// #define ACTION_DEBUG